In [1]:
%matplotlib inline


What is PyTorch?
===================

这是一个基于python的科学计算程序包，针对两类用户:

-  代替NumPy使用gpu的功能
-  提供最大灵活性的深度学习研究平台和速度

Getting Started
---------------



# Tensors


张量类似于NumPy的ndarrays，值得一提的是张量也可以用在GPU上加速计算。

In [2]:
from __future__ import print_function
import torch

构造一个5x3矩阵，未初始化:




In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[6.7377e-27, 9.4514e+21, 4.3121e-25],
        [5.5016e+11, 5.4593e+08, 1.5947e-42],
        [2.6573e+30, 1.6395e-43, 4.1055e-41],
        [9.3163e-39, 1.0150e+09, 2.5353e+30],
        [1.4013e-43, 4.6795e-41, 2.6177e+30]])


构造一个随机初始化矩阵:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7017, 0.6067, 0.4657],
        [0.8213, 0.3813, 0.4207],
        [0.4386, 0.9048, 0.6031],
        [0.0037, 0.3849, 0.5593],
        [0.4713, 0.2712, 0.9785]])



构造一个零矩阵并且数据格式是long型：

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


直接用数据构造一个张量:



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


或者在现有张量的基础上创建一个张量。这些方法将复制输入张量的属性，例如dtype数据类型，除非用户提供新的值



In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.5013,  1.2247,  0.3276],
        [ 0.5901, -0.5182,  1.2040],
        [ 0.8535,  1.2484, -1.1416],
        [ 0.9202, -1.6024,  1.2677],
        [-0.0405,  1.0447,  0.3324]])


获得size（）：


In [8]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` 实际上是一个元组，所以它支持所有的元组操作。</p></div>





# Operations

操作有多种语法。在下面的示例中，我们将研究加法操作。

加法: 语法 1

In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.2688,  1.7236,  0.9742],
        [ 0.8860, -0.2677,  1.8083],
        [ 1.3762,  2.1328, -0.1566],
        [ 1.5703, -1.4812,  1.7611],
        [ 0.8800,  1.1646,  0.5853]])


加法: 语法 2



In [10]:
print(torch.add(x, y))

tensor([[ 0.2688,  1.7236,  0.9742],
        [ 0.8860, -0.2677,  1.8083],
        [ 1.3762,  2.1328, -0.1566],
        [ 1.5703, -1.4812,  1.7611],
        [ 0.8800,  1.1646,  0.5853]])


加法: 提供第三个参数用来接加法的结果 3



In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.2688,  1.7236,  0.9742],
        [ 0.8860, -0.2677,  1.8083],
        [ 1.3762,  2.1328, -0.1566],
        [ 1.5703, -1.4812,  1.7611],
        [ 0.8800,  1.1646,  0.5853]])


加法: 用自己的成员函数



In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.2688,  1.7236,  0.9742],
        [ 0.8860, -0.2677,  1.8083],
        [ 1.3762,  2.1328, -0.1566],
        [ 1.5703, -1.4812,  1.7611],
        [ 0.8800,  1.1646,  0.5853]])


<div class="alert alert-info"><h4>Note</h4><p>任何使得张量发生改变的操作都是有小尾巴： ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

可以使用类似Numpy的索引方式来操作



In [13]:
print(x[:, 1])

tensor([ 1.2247, -0.5182,  1.2484, -1.6024,  1.0447])


调整大小: 如果你想调整张量的大小, 使用 ``torch.view``:



In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # 维度-1默认由其他维度初始化该维度
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


对于只有一个元素的张量, 使用 ``.item()`` 来获得他的具体值（没有缩略显示）




In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.8588])
-0.8588477373123169


# **Read later:**


  描述了100+张量运算，包括转置、标引、切片、数学运算、线性代数、随机数等
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

张量和Numpy的相互转化很简单

**Torch张量和NumPy数组将共享它们的底层内存位置(如果Torch张量位于CPU上)，更改其中一个将更改另一个。**

## 将张量转换为数字数组




In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


查看numpy数组的值是如何变化的。（对应的张量跟着一起变化）



In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Converting NumPy Array to Torch Tensor

查看如何改变np数组自动改变Torch张量



In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CPU上的所有张量，除了char型张量，都支持转换成
NumPy或者回转.

CUDA Tensors
------------

张量可以使用 ``.to`` 函数来转到驱动上去.



In [22]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # 初始化一个CUDA 对象
    y = torch.ones_like(x, device=device)  # 直接在GPU上创建一个张量对象
    x = x.to(device)                       # 或者直接调用   .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 可以同时改变数据类型!

tensor([0.1412], device='cuda:0')
tensor([0.1412], dtype=torch.float64)
